### PR TITLE
translate-meta-data-tokens-in-Chinese

### PR DESCRIPTION
**Pull request by xiaona423**
translation check required.

### CODE REVIEW

**Comment by Bee926** [comment]
Translation edited, good to go!

**Review by DarkGhost7 — APPROVED** [review]
lgtm needs tl checking

**Comment by DarkGhost7** [comment]
is this like a zombie pr of b401fa5835e28139a1b4a3e2213116439892caa1 ?

**Comment by DarkGhost7** [comment]
merged at https://github.com/yearn/yearn-meta/commit/b401fa5835e28139a1b4a3e2213116439892caa1 #close

**Pull request closed without merging**
