### PR TITLE
Update VesperFinance.json

### PR DESCRIPTION
**Pull request by xiaona423**
Vesper - zh

### CODE REVIEW

**Review by DarkGhost7 — APPROVED** [review]
lgtm @Bee926 could you tl check?

**Review by DarkGhost7 — APPROVED** [review]
lgtm

**Comment by Bee926** [comment]
> 

question, ghosty, what is lgtm?

**Comment by DarkGhost7** [comment]
looks good to me

**Comment by DarkGhost7** [comment]
@Bee926

**Pull request merged**
