### PR TITLE
feat: add new ftm strategies

### PR DESCRIPTION
**Pull request by DarkGhost7**

### CODE REVIEW

**Comment by DarkGhost7** [comment]
One moment a few more updates sorry

**Comment by DarkGhost7** [comment]
Ok good to merge / review now

**Comment by DarkGhost7** [comment]
Deleting leftover / not merged protocols let me know if this effects anything @dudesahn & @jstashh

**Comment by dudesahn** [comment]
@DarkGhost7 I believe the only BOO strategy we have right now is for 0xDAO, the xBOO staker ones aren't live yet

**Review by milkyklim — APPROVED** [review]

**Pull request merged**
