### PR TITLE
feat: add retired properties to vault [WEB-811]

### PR DESCRIPTION
**Pull request by jstashh**

### CODE REVIEW

**Comment by dudesahn** [comment]
@jstashh could you rename `Non-hidden vaults` to something like `visibleVaults` ? a bit concerned whether the spaces are going to cause any issues anywhere

**Comment by jstashh** [comment]
@dudesahn good point. Alternatively do you think we should remove the directory and just have all the vaults at the same level? Would make it a bit easier to fetch the data and not sure the directory is necessary, but if you want to keep it just so it's easier to reason about which vaults are hidden then that's also fine.

**Comment by jstashh** [comment]
@dudesahn renamed the directory to remove the space

**Comment by dudesahn** [comment]
@jstashh yeah actually I would def agree it's better just to have them all at the same level and kill the folder

**Comment by jstashh** [comment]
@dudesahn cool, have just pushed that

**Review by dudesahn — APPROVED** [review]

**Pull request merged**
